version: 2
discovery:
  allowed-hostnames:
    - localhost
  network-idle-timeout: 750
snapshot:
  widths:
    - 375   # Mobile
    - 768   # Tablet  
    - 1280  # Desktop
  min-height: 1024
  percy-css: |
    /* Hide dynamic content that changes between runs */
    .dynamic-timestamp { display: none !important; }
    .user-avatar { display: none !important; }
    /* Ensure consistent rendering */
    * { 
      animation-duration: 0s !important;
      animation-delay: 0s !important;
      transition-duration: 0s !important;
      transition-delay: 0s !important;
    }
# Static snapshots configuration removed - using Cypress integration instead 